alternate: keishispl

# Assets
statics: / #//cdn.jsdelivr.net/gh/amehime/shoka@latest/

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  about: /about/ || user

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/keishispl || github || "#191717"
  #google: https://plus.google.com/yourname || google
  twitter: https://twitter.com/keishispl || twitter || "#00aff0"
  #zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"
  #weibo: https://weibo.com/amehime || weibo || "#ea716e"
  #about: https://about.me/amehime || address-card || "#3b5998"
  #email: mailto:yourname@mail.com || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  youtube: https://youtube.com/@keishispl || youtube
  instagram: https://instagram.com/keishispl || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2026
  count: true

post:
  count: true


# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Comments
# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:

# bgm
audio:

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------


# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true
